### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by sgerrand** [emfigo/absplit#10]
I've left a [few](https://github.com/emfigo/absplit/pull/9#issuecomment-64786884) [comments](https://github.com/emfigo/absplit/pull/9#issuecomment-72178576) to this effect, but are you planning on releasing e6ae00b047 in a new gem version?

**Comment by sgerrand** [comment]
@emfigo: :wave:

**Comment by emfigo** [comment]
Solved in [PR](https://github.com/emfigo/absplit/pull/11)
